// Code generated by go-jenny(taylz.io/cmd/go-jenny@v0.0.0) DO NOT EDIT.

package user

import (
	"sync"
)

// Sockets is an observable concurrent in-memory datastore
type Sockets struct {
	dat map[string]bool
	mu  sync.Mutex
	obs []SocketsObserver
}

// SocketsGetter is a func(string)->bool
type SocketsGetter = func(string) bool

// SocketsObserver is a func(string, oldbool, newbool)
type SocketsObserver = func(string, bool, bool)

// SocketsSetter is a func(string,bool)
type SocketsSetter = func(string, bool)

// NewSockets returns a new Sockets
func NewSockets() *Sockets {
	return &Sockets{
		dat: make(map[string]bool),
		obs: make([]SocketsObserver, 0),
	}
}

// Get returns the bool for a string
func (this *Sockets) Get(k string) bool { return this.dat[k] }

// Set saves a bool for a string
func (this *Sockets) Set(k string, v bool) {
	this.mu.Lock()
	this.set(k, v)
	this.mu.Unlock()
}

func (this *Sockets) set(k string, v bool) {
	old := this.dat[k]
	if v != false {
		this.dat[k] = v
	} else {
		delete(this.dat, k)
	}
	for _, f := range this.obs {
		f(k, old, v)
	}
}

// Each calls the func for each string,bool in this Sockets
func (this *Sockets) Each(f SocketsSetter) {
	this.mu.Lock()
	for k, v := range this.dat {
		f(k, v)
	}
	this.mu.Unlock()
}

// Sync calls the func within the cache lock state
func (this *Sockets) Sync(f func(SocketsGetter, SocketsSetter)) {
	this.mu.Lock()
	f(this.Get, this.set)
	this.mu.Unlock()
}

// Keys returns a new slice with all the string keys
func (this *Sockets) Keys() []string {
	this.mu.Lock()
	keys := make([]string, 0, len(this.dat))
	for k := range this.dat {
		keys = append(keys, k)
	}
	this.mu.Unlock()
	return keys
}

// Observe adds a func to be called when a bool is set
func (this *Sockets) Observe(f SocketsObserver) { this.obs = append(this.obs, f) }

// Remove deletes a string,bool
func (this *Sockets) Remove(k string) { this.Set(k, false) }
