// Code generated by go-jenny(taylz.io/cmd/go-jenny@v0.0.0) DO NOT EDIT.

package user

import (
	"sync"

	"taylz.io/http/websocket/message"
)

// Sockets is an observable concurrent in-memory datastore
type Sockets struct {
	dat map[string]message.Writer
	mu  sync.Mutex
	obs []SocketsObserver
}

// SocketsGetter is a func(string)->message.Writer
type SocketsGetter = func(string) message.Writer

// SocketsObserver is a func(string, oldmessage.Writer, newmessage.Writer)
type SocketsObserver = func(string, message.Writer, message.Writer)

// SocketsSetter is a func(string,message.Writer)
type SocketsSetter = func(string, message.Writer)

// NewSockets returns a new Sockets
func NewSockets() *Sockets {
	return &Sockets{
		dat: make(map[string]message.Writer),
		obs: make([]SocketsObserver, 0),
	}
}

// Get returns the message.Writer for a string
func (this *Sockets) Get(k string) message.Writer { return this.dat[k] }

// Set saves a message.Writer for a string
func (this *Sockets) Set(k string, v message.Writer) {
	this.mu.Lock()
	this.set(k, v)
	this.mu.Unlock()
}

func (this *Sockets) set(k string, v message.Writer) {
	old := this.dat[k]
	if v != nil {
		this.dat[k] = v
	} else {
		delete(this.dat, k)
	}
	for _, f := range this.obs {
		f(k, old, v)
	}
}

// Each calls the func for each string,message.Writer in this Sockets
func (this *Sockets) Each(f SocketsSetter) {
	this.mu.Lock()
	for k, v := range this.dat {
		f(k, v)
	}
	this.mu.Unlock()
}

// Sync calls the func within the cache lock state
func (this *Sockets) Sync(f func(SocketsGetter, SocketsSetter)) {
	this.mu.Lock()
	f(this.Get, this.set)
	this.mu.Unlock()
}

// Keys returns a new slice with all the string keys
func (this *Sockets) Keys() []string {
	this.mu.Lock()
	keys := make([]string, 0, len(this.dat))
	for k := range this.dat {
		keys = append(keys, k)
	}
	this.mu.Unlock()
	return keys
}

// Observe adds a func to be called when a message.Writer is set
func (this *Sockets) Observe(f SocketsObserver) { this.obs = append(this.obs, f) }

// Remove deletes a string,message.Writer
func (this *Sockets) Remove(k string) { this.Set(k, nil) }
